
def find_max(words):
    """Write a function that accepts a list of strings.
    The list contains different words. Return the word with maximum number
    of unique characters. If multiple strings have maximum number of unique
    characters, return the one which comes first in lexicographical order.

    find_max(["name", "of", "string"]) == "string"
    find_max(["name", "enam", "game"]) == "enam"
    find_max(["aaaaaaa", "bb" ,"cc"]) == ""aaaaaaa"
    """
    return sorted(words)[0]
assert find_max(['hello', 'world', 'python']) == 'python'
assert find_max(['hello', 'world', 'python', 'programming']) == 'programming'
assert find_max(['hello', 'world', 'python', 'programming', 'language']) == 'programming'
assert find_max(['hello', 'world', 'python', 'java']) == 'python'
assert find_max(['hello', 'world', 'python', 'java', 'code']) == 'python'
assert find_max(['hello', 'world', 'python', 'java', 'code', 'programming']) == 'programming'
assert find_max(['hello', 'world', 'python', 'java', 'code', 'programming', 'problem']) == 'programming'
assert find_max(['apple', 'banana', 'cherry', 'date', 'elderberry']) == 'elderberry'
assert find_max(['a', 'aa', 'aaa']) == 'a'
assert find_max(['abc', 'def', 'ghi']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't']) == 'abc'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'c++', 'javascript']) == 'javascript'
assert find_max(['hello', 'hi']) == 'hello'
assert find_max(['hello', 'hi', 'world']) == 'world'
assert find_max(['aaa', 'bbb', 'ccc']) == 'aaa'
assert find_max(['python', 'java', 'javascript']) == 'javascript'
assert find_max(['abc', 'def', 'ghi', 'abc']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'abc', 'def']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'abc', 'def', 'ghi']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'abc', 'def', 'ghi', 'abc']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'abc', 'def', 'ghi', 'abc', 'def']) == 'abc'
assert find_max(['hello', 'world', 'python', 'programming', 'code']) == 'programming'
assert find_max(['cat', 'dog', 'elephant']) == 'elephant'
assert find_max(['a', 'b', 'c']) == 'a'
assert find_max(['abc', 'def', 'ghi', 'jkl']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl', 'mno']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl', 'mno', 'pqr']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'abc', 'def', 'ghi', 'jkl']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'abcd']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'zxcv']) == 'zxcv'
assert find_max(['abc', 'def', 'ghi', 'zxcv', 'abcd']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'zxcv', 'zxcv']) == 'zxcv'
assert find_max(['abc', 'def', 'ghi', 'zxcv', 'abcd', 'zxcv']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'zxcv', 'zxcv', 'abcd']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'zxcv', 'abc', 'zxcv', 'abcd']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'zxcv', 'abc', 'zxcv', 'abcd', 'abcd']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'zxcv', 'abc', 'zxcv', 'abcd', 'zxcv', 'abcd']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'zxcv', 'abc', 'zxcv', 'abcd', 'zxcv', 'zxcv', 'abcd']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'zxcv', 'abc', 'zxcv', 'abcd', 'zxcv', 'abc', 'zxcv', 'abcd']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'zxcv', 'abc', 'zxcv', 'abcd', 'zxcv', 'abcd', 'abc', 'zxcv', 'abcd']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'def']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'def', 'ghi']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'def', 'ghi', 'abc']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'def', 'ghi', 'abc', 'xyz']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'def', 'ghi', 'abc', 'xyz', 'xyz']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'def', 'ghi', 'abc', 'xyz', 'xyz', 'xyz']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'def', 'ghi', 'abc', 'xyz', 'xyz', 'xyz', 'xyz']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'def', 'ghi', 'abc', 'xyz', 'xyz', 'xyz', 'xyz', 'abc']) == 'abc'
assert find_max(["hello", "world", "python", "java"]) == "python"
assert find_max(["hello", "world", "python", "java", "ruby"]) == "python"
assert find_max(["hello", "world", "python", "java", "ruby", "perl"]) == "python"
assert find_max(["hello", "world", "python", "java", "ruby", "perl", "scala"]) == "python"
assert find_max(['hello', 'world', 'python', 'java', 'ruby']) == 'python'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'c++']) == 'python'
assert find_max(['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig']) == 'elderberry'
assert find_max(['apple', 'banana', 'cherry', 'date', 'elderberry', 'fig', 'grape']) == 'elderberry'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr', 'stu', 'vwx', 'yz', 'a']) == 'abc'
assert find_max(["cat", "dog", "elephant"]) == "elephant"
assert find_max(['hello', 'world', 'programming']) == 'programming'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcde']) == 'abcde'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcde', 'defgh']) == 'abcde'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcde', 'defgh', 'abcde']) == 'abcde'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcde', 'defgh', 'abcde', 'defgh']) == 'abcde'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcde', 'defgh', 'abcde', 'defgh', 'abcdefgh']) == 'abcdefgh'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcde', 'defgh', 'abcde', 'defgh', 'abcdefgh', 'ijklmnop', 'qrstuvwxyz', 'abcdefghijklmnopqrstuvwxyz']) == 'abcdefghijklmnopqrstuvwxyz'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcde', 'defgh', 'abcde', 'defgh', 'abcdefgh', 'ijklmnop', 'qrstuvwxyz', 'abcdefghijklmnopqrstuvwxyz', 'abcdefghijklmnopqrstuvwxyz']) == 'abcdefghijklmnopqrstuvwxyz'
assert find_max(['abc', 'def', 'abc']) == 'abc'
assert find_max(['abc', 'def', 'abcdef']) == 'abcdef'
assert find_max(['abc', 'def', 'abcdefg']) == 'abcdefg'
assert find_max(['abc', 'def', 'abcdefg', 'hijklmnopqrstuvwxyz']) == 'hijklmnopqrstuvwxyz'
assert find_max(['abc', 'def', 'abcdefg', 'hijklmnopqrstuvwxyz', 'abcdefghijklmnopqrstuvwxyz']) == 'abcdefghijklmnopqrstuvwxyz'
assert find_max(["abc", "def", "ghi", "jkl"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz", "zz"]) == "abc"
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript']) == 'javascript'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abc']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'ab']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'ab', 'a']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'ab', 'a', 'abc']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'ab', 'a', 'abc', 'def']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'ab', 'a', 'abc', 'def', 'ghi']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'ab', 'a', 'abc', 'def', 'ghi', 'jkl']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'ab', 'a', 'abc', 'def', 'ghi', 'jkl', 'ab']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'ab', 'a', 'abc', 'def', 'ghi', 'jkl', 'ab', 'a']) == 'abc'
assert find_max(['abc', 'def', 'ab']) == 'abc'
assert find_max(['hello', 'world', 'python', 'programming', 'algorithm']) == 'algorithm'
assert find_max(['hello', 'world', 'python', 'programming', 'algorithm', 'data']) == 'algorithm'
assert find_max(['hello', 'world', 'python', 'programming', 'algorithm', 'data', 'structure']) == 'algorithm'
assert find_max(["a", "b", "c"]) == "a"
assert find_max(["abc", "def", "ghi"]) == "abc"
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'php']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'php', 'html']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'php', 'html', 'css']) == 'javascript'
assert find_max(['a', 'aa', 'aaa', 'aaaa']) == 'a'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'c++']) == 'javascript'
assert find_max(['a' * 1000000, 'b' * 1000000, 'c' * 1000000, 'd' * 1000000, 'e' * 1000000]) == 'a' * 1000000
assert find_max(['a' * 1000000, 'b' * 1000000, 'c' * 1000000, 'd' * 1000000, 'e' * 1000000, 'f' * 1000000]) == 'a' * 1000000
assert find_max(['a' * 1000000, 'b' * 1000000, 'c' * 1000000, 'd' * 1000000, 'e' * 1000000, 'f' * 1000000, 'g' * 1000000]) == 'a' * 1000000
assert find_max(['a' * 1000000, 'b' * 1000000, 'c' * 1000000, 'd' * 1000000, 'e' * 1000000, 'f' * 1000000, 'g' * 1000000, 'h' * 1000000]) == 'a' * 1000000
assert find_max(["a", "aa", "aaa"]) == "a"
assert find_max(["abc", "def", "ghi", "abc"]) == "abc"
assert find_max(['abc', 'def', 'ghij']) == 'ghij'
assert find_max(['python', 'java', 'ruby', 'javascript']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'python']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'python', 'java']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'python', 'java', 'ruby']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'python', 'java', 'ruby', 'hello']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'python', 'java', 'ruby', 'hello', 'world']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'python', 'java', 'ruby', 'hello', 'world', 'python']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'python', 'java', 'ruby', 'hello', 'world', 'python', 'java']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'python', 'java', 'ruby', 'hello', 'world', 'python', 'java', 'ruby']) == 'javascript'
assert find_max(['apple', 'banana', 'cherry', 'dog', 'elephant']) == 'elephant'
assert find_max(['apple', 'banana', 'cherry', 'dog', 'elephant', 'frog']) == 'elephant'
assert find_max(['apple', 'banana', 'cherry', 'dog', 'elephant', 'frog', 'gorilla']) == 'elephant'
assert find_max(["abcd", "efgh", "ijkl"]) == "abcd"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz", "abc"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz", "abc", "def"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz", "abc", "def", "ghi"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz", "abc", "def", "ghi", "jkl"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz", "abc", "def", "ghi", "jkl", "mno"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz", "abc", "def", "ghi", "jkl", "mno", "pqr"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz", "abc", "def", "ghi", "jkl", "mno", "pqr", "stu"]) == "abc"
assert find_max(["abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx", "yz", "abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vwx"]) == "abc"
assert find_max(['abc', 'def', 'ghi', 'abcde']) == 'abcde'
assert find_max(['cat', 'dog', 'elephant', 'giraffe']) == 'elephant'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard', 'monkey']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard', 'monkey', 'neon']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard', 'monkey', 'neon', 'owl']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard', 'monkey', 'neon', 'owl', 'parrot']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard', 'monkey', 'neon', 'owl', 'parrot', 'quail']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard', 'monkey', 'neon', 'owl', 'parrot', 'quail', 'rabbit']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard', 'monkey', 'neon', 'owl', 'parrot', 'quail', 'rabbit', 'snake']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard', 'monkey', 'neon', 'owl', 'parrot', 'quail', 'rabbit', 'snake', 'tiger']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard', 'monkey', 'neon', 'owl', 'parrot', 'quail', 'rabbit', 'snake', 'tiger', 'unicorn']) == 'hippopotamus'
assert find_max(['cat', 'dog', 'elephant', 'giraffe', 'hippopotamus', 'iguana', 'jaguar', 'kangaroo', 'leopard', 'monkey', 'neon', 'owl', 'parrot', 'quail', 'rabbit', 'snake', 'tiger', 'unicorn', 'vulture']) == 'hippopotamus'
assert find_max(['hello', 'world', 'python', 'java', 'ruby', 'javascript', 'haskell']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'javascript']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'javascript']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'javascript', 'ruby']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'javascript', 'ruby', 'c++']) == 'javascript'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno']) == 'abc', 'Test Case 2 Failed'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'mno', 'pqr']) == 'abc', 'Test Case 3 Failed'
assert find_max(["apple", "banana", "cherry", "date", "elderberry"]) == "elderberry"
assert find_max(["cat", "dog", "elephant", "giraffe"]) == "elephant"
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcd']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcd', 'efgh']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcd', 'efgh', 'ijkl']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcd', 'efgh', 'ijkl', 'lmno']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcd', 'efgh', 'ijkl', 'lmno', 'mnop']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'jkl', 'abcd', 'efgh', 'ijkl', 'lmno', 'mnop', 'nopq']) == 'abcd'
assert find_max(['abc', 'def', 'ghi', 'xyz']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'xyz', 'abc']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'xyz', 'abcd']) == 'abcd'
assert find_max(['python', 'programming', 'language']) == 'programming'
assert find_max(['abc', 'cba']) == 'abc'
assert find_max(['abc', 'abc', 'abc']) == 'abc'
assert find_max(['hello', 'world', 'python', 'programming', 'java']) == 'programming'
assert find_max(['hello', 'world', 'python', 'programming', 'java', 'ruby']) == 'programming'
assert find_max(['hello', 'world', 'python', 'programming', 'java', 'cpp']) == 'programming'
assert find_max(['hello', 'world', 'python', 'programming', 'java', 'cpp', 'csharp']) == 'programming'
assert find_max(['hello', 'world', 'python', 'programming', 'java', 'cpp', 'csharp', 'ruby']) == 'programming'
assert find_max(['hello', 'world', 'python', 'program']) == 'program'
assert find_max(['hello', 'world', 'python', 'apple']) == 'python'
assert find_max(["abc", "cba", "bac"]) == "abc"
assert find_max(['abc', 'def', 'ghi', 'jklm']) == 'jklm'
assert find_max(['abc', 'def', 'ghi', 'jklm', 'nopq']) == 'jklm'
assert find_max(['def', 'abc', 'ghi', 'jkl', 'mno', 'pqr']) == 'abc'
assert find_max(['def', 'ghi', 'abc', 'jkl', 'mno', 'pqr']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'abc', 'mno', 'pqr']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'abc', 'pqr']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(['def', 'ghi', 'jkl', 'mno', 'pqr', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc']) == 'abc'
assert find_max(["hello", "world", "python", "programming"]) == "programming"
assert find_max(["hello", "world", "python", "programming", "language"]) == "programming"
assert find_max(['hello', 'world', 'python', 'programming', 'code', 'java']) == 'programming'
assert find_max(['hello', 'world', 'python', 'program', 'coding']) == 'coding'
assert find_max(['hello', 'world', 'python', 'program', 'coding', 'language']) == 'coding'
assert find_max(['hello', 'world', 'python', 'program', 'coding', 'language', 'computer']) == 'computer'
assert find_max(['hello', 'world', 'python', 'java', 'javascript', 'ruby', 'perl']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'javascript', 'ruby', 'perl', 'go']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'javascript', 'ruby', 'perl', 'go', 'swift']) == 'javascript'
assert find_max(['hello', 'world', 'python', 'java', 'javascript', 'ruby', 'perl', 'go', 'swift', 'kotlin']) == 'javascript'
assert find_max(['hi', 'hello', 'hey']) == 'hello'
assert find_max(['apple', 'banana', 'cherry', 'date', 'eggplant']) == 'eggplant'
assert find_max(['abc', 'def', 'ghi', 'cba']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'cba', 'fed']) == 'abc'
assert find_max(['abc', 'def', 'ghi', 'cba', 'fed', 'cba']) == 'abc'
assert find_max(["aa", "bb", "cc"]) == "aa"
