from typing import List


def filter_by_substring(strings: List[str], substring: str) -> List[str]:
    """ Filter an input list of strings only for ones that contain given substring
    >>> filter_by_substring([], 'a')
    []
    >>> filter_by_substring(['abc', 'bacd', 'cde', 'array'], 'a')
    ['abc', 'bacd', 'array']
    """
    return [x for x in strings if x in substring]
assert filter_by_substring(["apple", "banana", "orange"], "an") == ["banana", "orange"]
assert filter_by_substring(["apple", "banana", "orange"], "le") == ["apple"]
assert filter_by_substring(["apple", "banana", "orange"], "pe") == []
assert filter_by_substring([], "an") == []
assert filter_by_substring(["apple", "banana", "orange"], "") == ["apple", "banana", "orange"]
assert filter_by_substring(['apple', 'banana', 'cherry', 'date'], 'b') == ['banana']
assert filter_by_substring(['apple', 'banana', 'cherry', 'date'], 'c') == ['cherry']
assert filter_by_substring(['apple', 'banana', 'cherry', 'date'], 'd') == ['date']
assert filter_by_substring(['apple', 'banana', 'cherry', 'date'], 'f') == []
assert filter_by_substring(['apple', 'banana', 'cherry'], 'melon') == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "z") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "") == ["apple", "banana", "cherry", "date"]
assert filter_by_substring(['hello', 'world', 'python'], 'l') == ['hello', 'world']
assert filter_by_substring(['hello', 'world', 'python'], 'z') == []
assert filter_by_substring(['hello', 'world', 'python'], '') == ['hello', 'world', 'python']
assert filter_by_substring(['apple', 'banana', 'cherry'], 'b') == ['banana']
assert filter_by_substring(['apple', 'banana', 'cherry'], 'c') == ['cherry']
assert filter_by_substring(['apple', 'banana', 'cherry'], 'd') == []
assert filter_by_substring(['apple', 'banana', 'cherry'], '') == ['apple', 'banana', 'cherry']
assert filter_by_substring(['hello', 'world', 'hi', 'bye'], 'hi') == ['hi']
assert filter_by_substring(['hello', 'world', 'hi', 'bye'], 'z') == []
assert filter_by_substring(["apple", "banana", "cherry"], "pear") == []
assert filter_by_substring(["apple", "banana", "cherry"], "b") == ["banana"]
assert filter_by_substring(["apple", "banana", "cherry"], "c") == ["cherry"]
assert filter_by_substring(["apple", "banana", "cherry"], "d") == []
assert filter_by_substring(['apple', 'banana', 'cherry'], 'e') == ['apple', 'cherry']
assert filter_by_substring(['apple', 'banana', 'cherry'], 'x') == []
assert filter_by_substring(["hello", "world", "python", "programming"], "l") == ["hello", "world"]
assert filter_by_substring(["hello", "world", "python", "programming"], "z") == []
assert filter_by_substring(["hello", "world", "python", "programming"], "") == ["hello", "world", "python", "programming"]
assert filter_by_substring(["hello", "world", "hi"], "l") == ["hello", "world"]
assert filter_by_substring(["hello", "world", "hi"], "x") == []
assert filter_by_substring(["hello", "world", "hi"], "") == ["hello", "world", "hi"]
assert filter_by_substring(["hello", "world", "python"], "l") == ["hello", "world"]
assert filter_by_substring(["hello", "world", "python"], "py") == ["python"]
assert filter_by_substring(["hello", "world", "python"], "x") == []
assert filter_by_substring(["hello", "world", "python"], "") == ["hello", "world", "python"]
assert filter_by_substring(['apple', 'banana', 'cherry'], 'peach') == []
assert filter_by_substring([], 'an') == []
assert filter_by_substring(["hello", "world", "python"], "z") == []
assert filter_by_substring(['hello', 'world', 'python', 'programming'], 'z') == []
assert filter_by_substring(['hello', 'world', 'python', 'programming'], 'ing') == ['programming']
assert filter_by_substring(["hello", "world", "python"], "llo") == ["hello"]
assert filter_by_substring(['apple', 'banana', 'cherry'], 'ap') == ['apple']
assert filter_by_substring(['hello', 'world', 'python'], 'py') == ['python']
assert filter_by_substring(['hello', 'world', 'python'], 'x') == []
assert filter_by_substring(["apple", "banana", "cherry"], "an") == ["banana"]
assert filter_by_substring(["apple", "banana", "cherry"], "r") == ["cherry"]
assert filter_by_substring(["apple", "banana", "cherry"], "x") == []
assert filter_by_substring(["apple", "banana", "cherry"], "") == ["apple", "banana", "cherry"]
assert filter_by_substring(["hello", "world", "python", "programming"], "g") == ["programming"]
assert filter_by_substring(["hello", "world", "python"], "python") == ["python"]
assert filter_by_substring([], "o") == []
assert filter_by_substring([], 'a') == []
assert filter_by_substring([], '') == []
assert filter_by_substring(['apple', 'banana', 'cherry'], 'an') == ['banana']
assert filter_by_substring(['apple', 'banana', 'cherry'], 'ch') == ['cherry']
assert filter_by_substring(['apple', 'banana', 'cherry'], 'rr') == ['cherry']
assert filter_by_substring(["cat", "dog", "fish"], "x") == []
assert filter_by_substring(['hello', 'world', 'python', 'programming'], 'l') == ['hello', 'world']
assert filter_by_substring(['hello', 'world', 'python', 'programming'], 'p') == ['python', 'programming']
assert filter_by_substring(["hello", "world", "python", "programming"], "x") == []
assert filter_by_substring(["hello", "world", "python", "programming"], "ing") == ["programming"]
assert filter_by_substring(["apple", "banana", "orange"], "x") == []
assert filter_by_substring([], 'o') == []
assert filter_by_substring(['hello', 'world', 'python', 'programming'], 'x') == []
assert filter_by_substring(['hello', 'world', 'python', 'programming'], '') == ['hello', 'world', 'python', 'programming']
assert filter_by_substring(["hello", "world", "python"], "ld") == ["world"]
assert filter_by_substring(['apple', 'banana', 'orange'], 'a') == ['apple', 'banana', 'orange']
assert filter_by_substring(['apple', 'banana', 'orange'], 'e') == ['apple', 'orange']
assert filter_by_substring(['apple', 'banana', 'orange'], 'x') == []
assert filter_by_substring(['hello', 'world', 'python'], 'p') == ['python']
assert filter_by_substring(['apple', 'banana', 'cherry', 'date'], '') == ['apple', 'banana', 'cherry', 'date']
assert filter_by_substring(["apple", "banana", "cherry", "date"], "b") == ["banana"]
assert filter_by_substring(["apple", "banana", "cherry", "date"], "c") == ["cherry"]
assert filter_by_substring(["apple", "banana", "cherry", "date"], "d") == ["date"]
assert filter_by_substring(["apple", "banana", "cherry", "date"], "f") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "g") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "i") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "j") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "k") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "m") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "o") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "q") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "s") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "u") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "v") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "w") == []
assert filter_by_substring(["apple", "banana", "cherry", "date"], "x") == []
assert filter_by_substring(['hello', 'world', 'python'], 'llo') == ['hello']
assert filter_by_substring(['cat', 'dog', 'bird', 'fish'], 'd') == ['dog', 'bird']
assert filter_by_substring(['apple', 'banana', 'cherry'], 'a') == ['apple', 'banana']
assert filter_by_substring(['apple', 'banana', 'cherry'], 'xyz') == []
assert filter_by_substring(["apple", "banana", "orange"], "b") == ["banana"]
assert filter_by_substring(["apple", "banana", "orange"], "c") == []
assert filter_by_substring(["apple", "banana", "orange"], "e") == ["apple", "orange"]
assert filter_by_substring(["apple", "banana", "orange"], "n") == ["banana", "orange"]
assert filter_by_substring(['hello', 'world', 'python'], 'python') == ['python']
assert filter_by_substring(['hello', 'world', 'python'], 'd') == ['world']
assert filter_by_substring(['cat', 'dog', 'fish'], 'z') == []
assert filter_by_substring(['hello', 'world', 'python'], 'y') == ['python']
assert filter_by_substring(['apple', 'banana', 'cherry', 'date'], 'an') == ['banana']
assert filter_by_substring(['apple', 'banana', 'cherry', 'date'], 'z') == []
