
def total_match(lst1, lst2):
    '''
    Write a function that accepts two lists of strings and returns the list that has 
    total number of chars in the all strings of the list less than the other list.

    if the two lists have the same number of chars, return the first list.

    Examples
    total_match([], []) ➞ []
    total_match(['hi', 'admin'], ['hI', 'Hi']) ➞ ['hI', 'Hi']
    total_match(['hi', 'admin'], ['hi', 'hi', 'admin', 'project']) ➞ ['hi', 'admin']
    total_match(['hi', 'admin'], ['hI', 'hi', 'hi']) ➞ ['hI', 'hi', 'hi']
    total_match(['4'], ['1', '2', '3', '4', '5']) ➞ ['4']
    '''
    l1 = 0
    for st in lst1:
        l1 += len(st)
    
    l2 = 0
    for st in lst2:
        l2 += len(st)
    
    if l1 <= l2:
        return lst2
    else:
        return lst1
assert total_match(['abc', 'def'], ['ghi', 'jkl']) == ['abc', 'def']
assert total_match(['qwertyuiopasdfghjklzxcvbnm', '123', '12345'], ['qwertyuiopasdfghjklzxcvbnm']) == ['qwertyuiopasdfghjklzxcvbnm']
assert total_match(['a','b','c','d'], ['a','b','c','e']) == ['a','b','c','d']
assert total_match(['a','b','c','d'], ['a','b','c','d']) == ['a','b','c','d']
assert total_match(['a','b','c','d'], ['a','b','c','d','e']) == ['a','b','c','d']
assert total_match(['pup', 'up', 'pop', 'pop'], ['pup', 'up', 'pop']) == ['pup', 'up', 'pop']
assert total_match(['pup', 'up', 'pop', 'pop'], ['pup', 'up', 'pop', 'pop', 'pop']) == ['pup', 'up', 'pop', 'pop']
assert total_match([""], [""]) == [""]
assert total_match(["a", "b", "c"], ["a", "b", "c"]) == ["a", "b", "c"]
assert total_match(["a", "b", "c", "d", "e", "f"], ["a", "b", "d", "e"]) == ["a", "b", "d", "e"]
assert total_match([ 'dog', 'cat','mat' ], ['dog', 'cat','mat']) == ['dog', 'cat','mat']
assert total_match(['a', 'b'], ['a', 'c']) == ['a', 'b']
assert total_match(['a', 'b', 'c', 'd'], ['a', 'b', 'c', 'e']) == ['a', 'b', 'c', 'd']
assert total_match(["abc", "def"], ["abc"]) == ["abc"]
assert total_match(["abc", "def"], ["ab", "def", "ghi", "jkl"]) == ["abc", "def"]
assert total_match(["abc", "def"], ["ab", "c", "ef", "ghi"]) == ["abc", "def"]
assert total_match(["abc", "def"], ["ab", "c", "ef", "ghi", "jkl"]) == ["abc", "def"]
assert total_match(["abc", "def"], ["ab", "c", "ef", "ghi", "jkl", "mno"]) == ["abc", "def"]
assert total_match(["abc", "def"], ["ab", "c", "ef", "ghi", "jkl", "mno", "pqr", "stu"]) == ["abc", "def"]
assert total_match(["abc", "def"], ["ab", "c", "ef", "ghi", "jkl", "mno", "pqr", "stu", "vwx"]) == ["abc", "def"]
assert total_match(["hello", "goodbye", "hey", "okay"], ["hello"]) == ["hello"]
assert total_match(["hello", "goodbye", "hey", "okay"], ["hello", "goodbye"]) == ["hello", "goodbye"]
assert total_match(['A', 'B', 'C'], ['A', 'B', 'C', 'd']) == ['A', 'B', 'C']
assert total_match(['A', 'B', 'C', 'D'], ['A', 'B', 'C', 'D']) == ['A', 'B', 'C', 'D']
assert total_match(['A', 'B', 'C'], ['A', 'B', 'C']) == ['A', 'B', 'C']
assert total_match(['A', 'B', 'C', 'd'], ['A', 'B', 'C', 'd']) == ['A', 'B', 'C', 'd']
assert total_match([], "foo") == []
assert total_match(['a', 'b', 'c'], ['a', 'b', 'e', 'f']) == ['a', 'b', 'c']
assert total_match(['a', 'b', 'c'], ['a', 'b', 'e']) == ['a', 'b', 'c']
assert total_match(['d'], ['a', 'b', 'c']) == ['d']
assert total_match([], []) == []
assert total_match([ 'a', 'b', 'c' ], [ 'c', 'b', 'a' ]) == [ 'a', 'b', 'c' ]
assert total_match([ 'a', 'b', 'c' ], [ 'c', 'a', 'b' ]) == [ 'a', 'b', 'c' ]
assert total_match([ 'a', 'b', 'c' ], [ 'c', 'a', 'b', 'c' ]) == [ 'a', 'b', 'c' ]
assert total_match([ 'a', 'b', 'c' ], [ 'a', 'b', 'c', 'd' ]) == [ 'a', 'b', 'c' ]
assert total_match(['h', 'e', 'l', 'l', 'o'], ['t', 'h', 'e', 'l', 'l', 'o']) == ['h', 'e', 'l', 'l', 'o']
assert total_match(['h', 'e', 'l', 'l', 'o'], ['s', 'u','s', 't', 'h', 'e', 'l', 'l', 'o']) == ['h', 'e', 'l', 'l', 'o']
assert total_match(['ABC'], ['ABC']) == ['ABC']
assert total_match(['ABC'], ['ABCD']) == ['ABC']
assert total_match(['ABC', 'DE'], ['ABC', 'DE']) == ['ABC', 'DE']
assert total_match(['ABC', 'DE'], ['ABC', 'ED']) == ['ABC', 'DE']
assert total_match(['ABC', 'DE'], ['ABC', 'DEE']) == ['ABC', 'DE']
assert total_match(['a','b','c','d'], ['c','b','a','d']) == ['a','b','c','d']
assert total_match(['a','b','c','d'], ['c','b','a','e']) == ['a','b','c','d']
assert total_match(['i', 'like', 'apple','mango', 'banana', 'orange','strawberry'], ['i', 'like', 'apple','mango', 'banana', 'orange','strawberry']) == ['i', 'like', 'apple','mango', 'banana', 'orange','strawberry'], "Check your code for total_match"
assert total_match(["apple", "banana", "cherry"], ["apple", "banana", "cherry"]) == ["apple", "banana", "cherry"]
assert total_match(["banana", "apple"], ["apple", "banana"]) == ["banana", "apple"]
assert total_match(["apple", "apple"], ["apple", "apple"]) == ["apple", "apple"]
assert total_match(["apple"], ["apple"]) == ["apple"]
assert total_match(["1", "2", "3"], []) == []
assert total_match(["1", "2", "3"], ["1", "2"]) == ["1", "2"]
assert total_match(['A', 'B', 'C', 'D', 'E'], ['A', 'B', 'C', 'D', 'E']) == ['A', 'B', 'C', 'D', 'E']
assert total_match(['A', 'B', 'C', 'D', 'E', 'AA'], ['A', 'B', 'C', 'D', 'E']) == ['A', 'B', 'C', 'D', 'E']
assert total_match(['A', 'B', 'C', 'D', 'E', 'AA'], ['A', 'B', 'C', 'D', 'E', 'AA']) == ['A', 'B', 'C', 'D', 'E', 'AA']
assert total_match(["aa", "bb", "cc"], ["cc", "dd", "ee"]) == ["aa", "bb", "cc"]
assert total_match(["foo"], ["foo"]) == ["foo"]
assert total_match([""], ["foo", "bar"]) == [""]
assert total_match(["foo", "bar"], ["foo", "bar"]) == ["foo", "bar"]
assert total_match(["a", "b", "c"], ["c", "ab", "a"]) == ["a", "b", "c"]
assert total_match(["a", "b", "c"], ["a"]) == ["a"]
assert total_match(["a", "b", "c"], ["b", "c"]) == ["b", "c"]
assert total_match(["a", "b", "c", "d"], ["d", "e"]) == ["d", "e"]
assert total_match(["a", "b", "c", "d"], ["e"]) == ["e"]
assert total_match(["a"], ["b"]) == ["a"]
assert total_match(["a", "b", "c", "d"], ["a"]) == ["a"]
assert total_match([""], ["", ""]) == [""]
assert total_match([""], []) == [""]
assert total_match([], [""]) == []
assert total_match(["asdf"], ["asdf"]) == ["asdf"]
assert total_match(['1', '2', '3'], ['4', '5', '6']) == ['1', '2', '3']
assert total_match(['h','o','c','o','m'], ['e','t','a','c','t']) == ['h','o','c','o','m']
assert total_match(['h','o','c','o','m'], ['r','e','a','c','t']) == ['h','o','c','o','m']
assert total_match(['h','o','c','o','m'], ['h','o','c','o','m']) == ['h','o','c','o','m']
assert total_match(["aaa", "", "bbb"], ["aaa"]) == ["aaa"]
assert total_match(["aaa", "bbb", "ccc"], ["aaa", "bbb"]) == ["aaa", "bbb"]
assert total_match(["a", "bbb", "ccc"], ["a", "bbb", "ccc"]) == ["a", "bbb", "ccc"]
assert total_match(['abc', 'def'], ['abc', 'def']) == ['abc', 'def']
assert total_match(['a', 'abc', 'ab'], ['', '']) == ['', '']
assert total_match(['a', 'a', 'a', 'a'], ['a', 'a', 'b', 'c']) == ['a', 'a', 'a', 'a']
assert total_match(['a', 'a', 'a', 'a'], ['a', 'b', 'a', 'c']) == ['a', 'a', 'a', 'a']
assert total_match(['a', 'a', 'a', 'a'], ['a', 'a', 'b', 'a']) == ['a', 'a', 'a', 'a']
assert total_match(['a', 'a', 'a', 'a'], ['a', 'a', 'b', 'c', 'a']) == ['a', 'a', 'a', 'a']
assert total_match(['apple', 'banana', 'grapes'], ['apple', 'pear']) == ['apple', 'pear']
assert total_match(['abc', 'abd'], ['abc', 'abd']) == ['abc', 'abd']
assert total_match(['a', 'b', 'd'], ['a', 'b', 'c']) == ['a', 'b', 'd']
assert total_match(['ab'], ['abc']) == ['ab']
assert total_match(['ab', 'abc', 'ab'], ['ab', 'ab']) == ['ab', 'ab']
assert total_match(['c', 'b'], ['a', 'd'])   == ['c', 'b']
assert total_match(['c', 'b'], ['a', 'b']) == ['c', 'b']
assert total_match(['c', 'b'], ['d', 'a'])   == ['c', 'b']
assert total_match(['c', 'b'], ['a', 'b', 'c']) == ['c', 'b']
assert total_match(['c', 'b'], ['d', 'a', 'b', 'c']) == ['c', 'b']
assert total_match(["abc"], ["abc", "def", "ghi"]) == ["abc"]
assert total_match(['a', 'b', 'c', 'd'], ['ab', 'cd']) == ['a', 'b', 'c', 'd']
assert total_match(['a', 'b', 'c', 'd'], ['b', 'a', 'b', 'c']) == ['a', 'b', 'c', 'd']
assert total_match([['hi', 'bye', 'bye', 'hi'], ['hi']], [['hi']])   == [['hi']]
assert total_match(['1', '2'], ['5', '4']) == ['1', '2']
assert total_match(['a','b','c'], ['d', 'e', 'f']) == ['a','b','c']
