
def select_words(s, n):
    """Given a string s and a natural number n, you have been tasked to implement 
    a function that returns a list of all words from string s that contain exactly 
    n consonants, in order these words appear in the string s.
    If the string s is empty then the function should return an empty list.
    Note: you may assume the input string contains only letters and spaces.
    Examples:
    select_words("Mary had a little lamb", 4) ==> ["little"]
    select_words("Mary had a little lamb", 3) ==> ["Mary", "lamb"]
    select_words("simple white space", 2) ==> []
    select_words("Hello world", 4) ==> ["world"]
    select_words("Uncle sam", 3) ==> ["Uncle"]
    """
    result = []
    for word in s.split():
        n_consonants = 0
        for i in range(0, len(word)):
            if word[i].lower() in ["a","e","i","o","u"]:
                n_consonants += 1 
        if n_consonants == n:
            result.append(word)
    return result

assert select_words("", 2) == []
assert select_words("hello world", 5) == []
assert select_words("h e l l o", 3) == []
assert select_words("h e l l o", 4) == []
assert select_words("hello world", 6) == []
assert select_words("hello world", 7) == []
assert select_words("hello world", 8) == []
assert select_words("hello world", 9) == []
assert select_words("hello world", 10) == []
assert select_words("hello world", 11) == []
assert select_words("", 0) == []
assert select_words("hello", 0) == []
assert select_words("hello", 1) == []
assert select_words("hello", 2) == []
assert select_words("hello", 3) == ['hello']
assert select_words("hello", 4) == []
assert select_words("hello", 5) == []
assert select_words("this is a test", 3) == ["this", "test"]
assert select_words("a e i o u", 0) == ["a", "e", "i", "o", "u"]
assert select_words("consonants", 4) == []
assert select_words("hello world", 0) == []
assert select_words("", 1) == []
assert select_words("hello", 6) == []
assert select_words("this is a test", 3) == ['this', 'test']
assert select_words("a e i o u", 0) == ['a', 'e', 'i', 'o', 'u']
assert select_words("hello world", 12) == []
assert select_words("hello world", 13) == []
assert select_words("hello world", 14) == []
assert select_words("hello world", 15) == []
assert select_words("hello world", 16) == []
assert select_words("hello world", 17) == []
assert select_words("hello world", 18) == []
assert select_words("hello world", 19) == []
assert select_words("hello world", 20) == []
assert select_words("hello world", 21) == []
assert select_words("hello world", 22) == []
assert select_words("hello world", 23) == []
assert select_words("hello world", 24) == []
assert select_words("hello world", 25) == []
assert select_words("hello world", 26) == []
assert select_words("hello world", 27) == []
assert select_words("hello world", 28) == []
assert select_words("hello world", 29) == []
assert select_words("hello world", 30) == []
assert select_words("hello world", 31) == []
assert select_words("hello world", 32) == []
assert select_words("hello world", 33) == []
assert select_words("hello world", 34) == []
assert select_words("hello world", 35) == []
assert select_words("hello world", 36) == []
assert select_words("hello world", 37) == []
assert select_words("hello world", 38) == []
assert select_words("hello world", 39) == []
assert select_words("hello world", 40) == []
assert select_words("hello world", 41) == []
assert select_words("hello world", 42) == []
assert select_words("hello world", 43) == []
assert select_words("hello world", 44) == []
assert select_words("hello world", 45) == []
assert select_words("hello world", 46) == []
assert select_words("hello world", 47) == []
assert select_words("hello world", 48) == []
assert select_words("hello world", 49) == []
assert select_words("hello world", 50) == []
assert select_words("hello world", 51) == []
assert select_words("hello world", 52) == []
assert select_words("hello world", 53) == []
assert select_words("hello world", 54) == []
assert select_words("hello world", 55) == []
assert select_words("hello world", 56) == []
assert select_words("hello world", 57) == []
assert select_words("hello world", 58) == []
assert select_words("hello world", 59) == []
assert select_words("hello world", 60) == []
assert select_words("hello world", 61) == []
assert select_words("hello world", 62) == []
assert select_words("hello world", 63) == []
assert select_words("hello world", 64) == []
assert select_words("hello world", 65) == []
assert select_words("hello world", 66) == []
assert select_words("hello world", 67) == []
assert select_words("hello world", 68) == []
assert select_words("hello world", 69) == []
assert select_words("hello world", 70) == []
assert select_words("hello world", 71) == []
assert select_words("hello world", 72) == []
assert select_words("hello world", 73) == []
assert select_words("hello world", 74) == []
assert select_words("hello world", 75) == []
assert select_words("hello world", 76) == []
assert select_words("hello world", 77) == []
assert select_words("hello world", 78) == []
assert select_words("hello world", 79) == []
assert select_words("hello world", 80) == []
assert select_words("hello world", 81) == []
assert select_words("hello world", 82) == []
assert select_words("hello world", 83) == []
assert select_words("hello world", 84) == []
assert select_words("hello world", 85) == []
assert select_words("hello world", 86) == []
assert select_words("hello world", 4) == ['world']
assert select_words("hello world", 2) == []
assert select_words("hello world", 3) == ["hello"]
assert select_words("", 4) == []
assert select_words("", 5) == []
assert select_words("hello world", 1) == []
assert select_words("hello world", 3) == ['hello']
assert select_words("a", 1) == []
assert select_words("a b", 2) == []
assert select_words("hello world", 4) == ["world"]
assert select_words("", 3) == []
assert select_words('hello world', 0) == []
assert select_words('hello world', 4) == ['world']
assert select_words('hello world', 5) == []
assert select_words('', 2) == []
assert select_words("apple banana cherry", 4) == []
assert select_words("no vowels here", 7) == []
