from typing import List, Optional


def longest(strings: List[str]) -> Optional[str]:
    """ Out of list of strings, return the longest one. Return the first one in case of multiple
    strings of the same length. Return None in case the input list is empty.
    >>> longest([])

    >>> longest(['a', 'b', 'c'])
    'a'
    >>> longest(['a', 'bb', 'ccc'])
    'ccc'
    """
    if not strings:
        return None

    maxlen = max(len(x) for x in strings)
    for s in strings:
        if len(s) > maxlen:
            return s
assert longest(["one", "two", "three"]) == "three"
assert longest(["one", "two", "three", "four", "five"]) == "three"
assert longest(["one", "two", "three", "four", "five", "six"]) == "three"
assert longest([]) is None
assert longest(["a", "bc", "abcd", "defg", "hijklmno"]) == "hijklmno"
assert longest(["abc"]) == "abc"
assert longest(["a", "ab", "ab", "abc"]) == "abc"
assert longest(["a", "ab", "abc", "ab"]) == "abc"
assert longest(["a", "ab", "abc"]) == "abc"
assert longest(["a", "ab", "abc", "def"]) == "abc"
assert longest(["a", "ab", "abc", "def", "f"]) == "abc"
assert longest(["a", "ab", "abc", "def", "f", "ghij"]) == "ghij"
assert longest(["a", "bc", "def", "ghij", "klmno"]) == "klmno"
assert longest(["a", "bc", "def", "ghij", "klmno", "pqrstu"]) == "pqrstu"
assert longest(["ef", "bc", "d", "gef", "a", "klmno", "pqrstu"]) == "pqrstu"
assert longest(["a", "bc", "def", "ghij", "klmno", "pqrstu", "vwxyz"]) == "pqrstu"
assert longest(["a", "bc", "def", "ghij", "klmno", "pqrstu", "vwxyz", "ef", "gef", "d"]) == "pqrstu"
assert longest(["a", "bb", "ccc", "dddd"]) == "dddd"
assert longest(["a", "bb", "ccc", "dddd", "eeeee"]) == "eeeee"
assert longest(["a", "bb", "ccc", "dddd", "eeeee", "ffff"]) == "eeeee"
assert longest(["aa", "bb", "ccc", "dddd", "eeeee", "ffff"]) == "eeeee"
assert longest(["aa", "bbb", "ccc", "dddd", "eeeee", "ffff"]) == "eeeee"
assert longest(["aa", "bbb", "ccc", "dddd", "eeeeee", "ffff"]) == "eeeeee"
assert longest(["aa", "bbb", "ccc", "dddd", "eeeeee", "fffff"]) == "eeeeee"
assert longest(["aa", "bbb", "ccc", "dddd", "eeeeee", "fff"]) == "eeeeee"
assert longest(["aa", "bbb", "ccc", "dddd", "eeeeee", "ff"]) == "eeeeee"
assert longest(["", ""]) == ""
assert longest(["", "", ""]) == ""
assert longest(["aaa", "bb", "ccccc"]) == "ccccc"
assert longest(["aaa", "bb", "ccccc", "ddddddddddddddddddddddddddddddddddd"]) == "ddddddddddddddddddddddddddddddddddd"
assert longest([""]) == ""
assert longest(["a"]) == "a"
assert longest(["", "a"]) == "a"
assert longest(["a", ""]) == "a"
assert longest(["", "a", ""]) == "a"
assert longest(["a", "", ""]) == "a"
assert longest(["", "", "a"]) == "a"
assert longest(["abc", "abcde", "abcdef"]) == "abcdef"
assert longest(["abc", "b", "c"]) == "abc"
assert longest(["ab"]) == "ab"
assert longest(["ab", "ab"]) == "ab"
assert longest(["ab", "ab", "ab"]) == "ab"
assert longest(["A", "list", "of", "strings"]) == "strings"
assert longest(["Python", "is", "great"]) == "Python"
assert longest(["And", "now", "some", "more", "strings"]) == "strings"
assert longest(["what", "an", "interesting", "example"]) == "interesting"
assert longest(["hello", "world"]) == "hello"
assert longest(["abc", "abc", "abc", "abc"]) == "abc"
assert longest(["abc", "def", "abcde", "abcd"]) == "abcde"
assert longest(["short", "longest", "longer", "longer"]) == "longest"
assert longest(["short", "longest", "longer", "longer", "longest"]) == "longest"
assert longest(["abc", "ab", "a"]) == "abc"
assert longest(["a", "ab", "abc", "abcde"]) == "abcde"
assert longest(["abcde", "abc", "ab", "a"]) == "abcde"
assert longest(["a", "ab", "abc", "abcd", "abcde"]) == "abcde"
assert longest(["abcde", "abcd", "abc", "ab", "a"]) == "abcde"
assert longest(["a", "ab", "abc", "abcd"]) == "abcd"
assert longest(["a", "ab", "abc", "abcd", "abcde", "abcdef"]) == "abcdef"
assert longest(["abcdef", "abcde", "abcd", "abc", "ab", "a"]) == "abcdef"
assert longest(["abcdef", "abcde", "abcd", "abc", "ab", "a", ""]) == "abcdef"
assert longest(["abcdef", "abcde", "abcd", "abc", "ab", "a", "", "a"]) == "abcdef"
assert longest(["abcdef", "abcde", "abcd", "abc", "ab", "a", "", "a", "abcdefg"]) == "abcdefg"
assert longest(["abcdef", "abcde", "abcd", "abc", "ab", "a", "", "a", "abcdefg", "abcdefgh"]) == "abcdefgh"
assert longest(["", "123"]) == "123"
assert longest(["123", ""]) == "123"
assert longest(["123", "22", "3"]) == "123"
assert longest(["111", "111", "11"]) == "111"
assert longest(["111", "222", "333"]) == "111"
assert longest(["", "1234", "12", "12"]) == "1234"
assert longest(["ab", "bc", "cd", "ef", "gh", "ii", "no", "pq", "rs", "tu", "vw", "xy", "zz", "123"]) == "123"
assert longest(["ab", "bc", "cd", "ef", "gh", "ii", "no", "pq", "rs", "tu", "vw", "xy", "zz", "123", "456"]) == "123"
assert longest(["tiger", "zebra", "aardvark"]) == "aardvark"
assert longest(["aaa", "aa", "a"]) == "aaa"
assert longest(["a", "bc", "def", "def"]) == "def"
assert longest(["abc", "abc", "abc"]) == "abc"
assert longest(["ab", "c", "a"]) == "ab"
assert longest(["", "ab", "abc"]) == "abc"
assert longest(["a", "ab", ""]) == "ab"
assert longest(["short", "longer"]) == "longer"
assert longest(["short", "loooooonger"]) == "loooooonger"
assert longest(["short", "longer", "looooooonger"]) == "looooooonger"
assert longest(["short", "longer", "short"]) == "longer"
assert longest(["longer", "short", "longer"]) == "longer"
assert longest(["longer", "longer", "short"]) == "longer"
assert longest(["longer", "short", "longer", "short"]) == "longer"
assert longest(["longer", "short", "short", "longer"]) == "longer"
assert longest(["short", "longer", "short", "longer"]) == "longer"
assert longest(["longer", "longer", "short", "short"]) == "longer"
assert longest(["short", "short", "longer", "longer"]) == "longer"
assert longest(["a", "abc", "ab"]) == "abc"
assert longest(["abc", "a", "ab"]) == "abc"
assert longest(["a", "ab", "abc", ""]) == "abc"
assert longest(["", "ab", "abc", ""]) == "abc"
assert longest(["abc", "cde", "def", "ab"]) == "abc"
assert longest(["boo", "meow", "caw", "heehaw"]) == "heehaw"
assert longest(["boo", "meow", "caw", "heehaw", "moo"]) == "heehaw"
assert longest(["", "meow", "caw", "heehaw", "moo"]) == "heehaw"
assert longest(["", "", "", "heehaw", "moo"]) == "heehaw"
assert longest(["", "", "", "heehaw", ""]) == "heehaw"
assert longest(["", "", "", "", ""]) == ""
assert longest(["sit", "amet", "consectetur", "adipiscing", "elit"]) == "consectetur"
assert longest(["a", "bb", "ccc"]) == "ccc"
assert longest(["Hello", "world", "!"]) == "Hello"
assert longest(["123", "12345", "123456789", "1"]) == "123456789"
assert longest(["ab", "abc", ""]) == "abc"
assert longest(["", "", "abc"]) == "abc"
assert longest(["ab", "", ""]) == "ab"
assert longest(["a", "aa", "aaa"]) == "aaa"
assert longest(["hello", "world", "!"]) == "hello"
assert longest(["dog", "caterpillar", "pig"]) == "caterpillar"
assert longest(["dog", "cat", "pig", "caterpillar"]) == "caterpillar"
assert longest(["dog", "cat", "pig", "caterpillar", "doggy"]) == "caterpillar"
assert longest(["hi", "bye", "cool", "awesome", "hey"]) == "awesome"
assert longest(["hi", "bye", "cool", "awesome", "hey", "hey"]) == "awesome"
assert longest(["123", "12", "1", "1234"]) == "1234"
assert longest(["123", "12", "12", "12"]) == "123"
assert longest(["one", "three", "two"]) == "three"
assert longest(["three", "one", "two"]) == "three"
assert longest(["three", "two", "one"]) == "three"
assert longest(["two", "one"]) == "two"
assert longest(["one"]) == "one"
assert longest(["str1", "str22", "str3"]) == "str22"
assert longest(["str1", "str222", "str3"]) == "str222"
assert longest(["ab", "abc", "a"]) == "abc"
assert longest(["abcd", "a", "ab", "abc"]) == "abcd"
assert longest(["abcde", "a", "ab", "abc", "abcd"]) == "abcde"
assert longest(["abcde", "a", "ab", "abc", "abcd", "abcde"]) == "abcde"
assert longest(["a", "ab", "abc", "abcd", "abcde", "abcde"]) == "abcde"
assert longest(["ab", "a", "abc"]) == "abc"
assert longest(["abcd", "ab", "abc", "a"]) == "abcd"
assert longest(["abc", "abcd", "ab", "a"]) == "abcd"
assert longest(["abcd", "abc", "ab", "a"]) == "abcd"
assert longest(["123", "12345", "123456", "1234", "1234567", "12345678"]) == "12345678"
assert longest(["123", "12345", "123456", "1234", "1234567", "12345678", "123456789"]) == "123456789"
assert longest(["123", "12345", "123456", "1234", "1234567", "12345678", "123456789", "1234567890"]) == "1234567890"
assert longest(["123", "12345", "123456", "1234", "1234567", "12345678", "123456789", "1234567890", "12345678901"]) == "12345678901"
assert longest(["123", "12345", "123456", "1234", "1234567", "12345678", "123456789", "1234567890", "12345678901", "123456789012"]) == "123456789012"
assert longest(["aaa", "aa", "aa"]) == "aaa"
assert longest(["a", "b", "c"]) == "a"
assert longest(["aaa", "bbbb", "c"]) == "bbbb"
assert longest(["aaa", "bbbb", "cc"]) == "bbbb"
assert longest(["abc", "defg", "ah", "pqrstu"]) == "pqrstu"
assert longest(["aaaa", "aaaa", "aaaa"]) == "aaaa"
assert longest(["ab", "a", "abc", "abcd"]) == "abcd"
assert longest(["test", "aaa", "ab"]) == "test"
assert longest(["aa", "a", "aaa"]) == "aaa"
assert longest(["aa", "a", "aaa", "a"]) == "aaa"
assert longest(["a", "aa", "aaa", "aaaa"]) == "aaaa"
assert longest(["a", "aa", "aa", "aa"]) == "aa"
assert longest(["aa"]) == "aa"
assert longest(["aaa"]) == "aaa"
assert longest(["aaaa"]) == "aaaa"
assert longest(["d", "ee", "fff"]) == "fff"
assert longest(["gggg", "hhh", "ii"]) == "gggg"
assert longest(["aa", "bbb", "c"]) == "bbb"
assert longest(["abcdef", "abc", "abcde", "abcdefgh", "a"]) == "abcdefgh"
assert longest(["a", "abc", "abcde", "abcdefgh"]) == "abcdefgh"
assert longest(["abcdef", "abc", "abcde", "abcdefgh", "abcdefg"]) == "abcdefgh"
assert longest(["A", "hello", "world", "z", "one", "two", "three", "four", "five"]) == "hello"
assert longest(["quick", "brown", "fox", "jumps", "over", "a", "lazy", "dog", "another", "word"]) == "another"
assert longest(["1234567", "12345678", "123456"]) == "12345678"
assert longest(["12345678", "1234567", "123456"]) == "12345678"
assert longest(["123456", "1234567", "12345678"]) == "12345678"
assert longest(["123456", "12345678", "1234567"]) == "12345678"
assert longest(["12345678", "123456", "1234567"]) == "12345678"
assert longest(["12345678"]) == "12345678"
assert longest(["123456"]) == "123456"
assert longest(["abc", "def", "ghi"]) == "abc"
assert longest(["def", "abc", "ghi"]) == "def"
assert longest(["ghi", "abc", "def"]) == "ghi"
assert longest(["abc", "def", "ghi", "jkl"]) == "abc"
assert longest(["jkl", "def", "ghi", "abc"]) == "jkl"
assert longest(["abc", "def", "ghi", "jkl", "mno"]) == "abc"
assert longest(["abc", "def", "ghi", "jkl", "mno", "pqr"]) == "abc"
assert longest(["def", "ghi", "jkl", "mno", "pqr", "abc"]) == "def"
assert longest(["ghi", "jkl", "mno", "pqr", "abc", "def"]) == "ghi"
assert longest(["jkl", "mno", "pqr", "abc", "def", "ghi"]) == "jkl"
assert longest(["123", "12", "12345"]) == "12345"
assert longest(["123", "12", "1", "12345"]) == "12345"
assert longest(["123", "12", "12345", "12345"]) == "12345"
assert longest(["abc", "ab", "abcd", "efgh"]) == "abcd"
assert longest(["abc", "ab", "abcd", "efgh", "foobar"]) == "foobar"
assert longest(["abcd", "ab", "abc", "efgh", "foobar"]) == "foobar"
assert longest(["abcd", "ab", "abc", "efgh", "foobar", "foobarbar"]) == "foobarbar"
assert longest(["", "ab"]) == "ab"
assert longest(["", "ab", ""]) == "ab"
assert longest(["x"]) == "x"
assert longest(["one", "hello", "world", "one and a half"]) == "one and a half"
assert longest(["one", "hello", "world", "one and a half", "one and a half"]) == "one and a half"
assert longest(["ghij", "bc", "def", "a"]) == "ghij"
assert longest(["ghij", "bc", "a", "def"]) == "ghij"
assert longest(["a", "bc", "def"]) == "def"
assert longest(["def", "bc", "a"]) == "def"
assert longest(["def", "a", "bc"]) == "def"
assert longest(["abc", "abcd", "abcd"]) == "abcd"
assert longest(["abcd", "ab"]) == "abcd"
assert longest(["abcd", "ab", "a"]) == "abcd"
assert longest(["a", "bc"]) == "bc"
assert longest(["abc", "a", "c"]) == "abc"
assert longest(["ab", "bb", "ccc", "dddd", "eeeee"]) == "eeeee"
assert longest(["a", "bb", "ccc", "dddd", "eeeee", "ffffff"]) == "ffffff"
assert longest(["ab", "bb", "ccc", "dddd", "eeeee", "ffffff"]) == "ffffff"
assert longest(["ab", "bb", "ccc", "dddd", "eeeee", "ffffff", "ggggggg"]) == "ggggggg"
assert longest(["aa", "bb", "ccc"]) == "ccc"
assert longest(["cat", "dog", "elephant"]) == "elephant"
assert longest(["cat", "dog", "elephant", "cat"]) == "elephant"
assert longest(["cat", "dog", "elephant", "dog"]) == "elephant"
assert longest(["aaa", "bbb", "ccc"]) == "aaa"
assert longest(["aaa", "bbb", "ccc", "ddd"]) == "aaa"
assert longest(["aaa", "bbb", "ccc", "ddd", "eee"]) == "aaa"
assert longest(["", "a", "ab", "abc"]) == "abc"
assert longest(["", "a", "ab", "abc", "abcde"]) == "abcde"
assert longest(["quick", "brown", "jumps", "over", "the"]) == "quick"
assert longest(["aa", "aa"]) == "aa"
assert longest(["a", "a", "a"]) == "a"
assert longest(["", "A", ""]) == "A"
assert longest(["abc", "ab", "abc"]) == "abc"
assert longest(["foo", "bar", "baz", "longer"]) == "longer"
assert longest(["longest", "longer", "long"]) == "longest"
assert longest(["same", "same", "same"]) == "same"
assert longest(["foo", "bar", "baz"]) == "foo"
assert longest(["12", "123", "123", "12"]) == "123"
assert longest(["123", "123", "123", "123"]) == "123"
assert longest(["short", "shortest", "shorter"]) == "shortest"
assert longest(["shortest", "short", "shorter"]) == "shortest"
assert longest(["shortest", "shorter", "short"]) == "shortest"
assert longest(["shorter", "short", "shortest"]) == "shortest"
assert longest(["shorter", "shortest", "short"]) == "shortest"
assert longest(["one", "one"]) == "one"
assert longest(["cat", "meow", "me", "m", "mew", "meow"]) == "meow"
assert longest(["my", "name", "is", "John", "Doe", "this", "one", "is", "longest"]) == "longest"
assert longest(["foo", "bar", "foobar"]) == "foobar"
assert longest(["foo", "bar", "foobar", "foobarbaz"]) == "foobarbaz"
assert longest(["ab", "a", "abcd", "abcde"]) == "abcde"
assert longest(["ab", "a", "abcd", "abcde", "abcd"]) == "abcde"
assert longest(["abcde", "abcde", "abcde"]) == "abcde"
assert longest(["abc", "abcd", "abcde"]) == "abcde"
assert longest([]) == None
assert longest(["one", "three", "twelve", "four", "five"]) == "twelve"
assert longest(["abc", "defg", "a"]) == "defg"
assert longest(["a", "abc", "abcde", "abcdef"]) == "abcdef"
assert longest(["1234567890", "a", "abc", "abcde", "abcdef", "abcdefg", "a" * 10]) == "1234567890"
assert longest(["abc", "d", "abcd", "efghi"]) == "efghi"
assert longest(["a", "ab", "abc", "abcde", "abcdef"]) == "abcdef"
assert longest(["a", "ab", "abc", "abcde", "abcdef", "abcdefg"]) == "abcdefg"
assert longest(["a", "ab", "abc", "abcde", "abcdef", "abcdefg", "abcdefgh"]) == "abcdefgh"
assert longest(["a", "ab", "abc", "abcde", "abcdef", "abcdefg", "abcdefgh", "abcdefghi"]) == "abcdefghi"
assert longest(["a", "ab", "abc", "abcde", "abcdef", "abcdefg", "abcdefgh", "abcdefghi", "abcdefghij"]) == "abcdefghij"
assert longest(["aaa", "bbb", "cc"]) == "aaa"
assert longest(["ccc", "bbb", "aaa"]) == "ccc"
assert longest(["cc", "bbb", "aaa"]) == "bbb"
assert longest(["cc", "bb", "aaa"]) == "aaa"
assert longest(["longest", "longer", "longest", "medium"]) == "longest"
assert longest(["short", "longer", "medium"]) == "longer"
assert longest(["short", "short", "short"]) == "short"
assert longest(["short"]) == "short"
assert longest(["short", "short"]) == "short"
assert longest(["", "a", "ab"]) == "ab"
assert longest(["abc", "ab", "abcde"]) == "abcde"
assert longest(["abc", "ab", ""]) == "abc"
assert longest(["", "ab", "ab"]) == "ab"
assert longest(["not", "this", "test"]) == "this"
assert longest(["a", "little", "test"]) == "little"
assert longest(["abcd", "abcde", "abcdef", "abc"]) == "abcdef"
assert longest(["abcd", "abcde", "abcdef", "abc", "bcdef"]) == "abcdef"
assert longest(["hello"]) == "hello"
assert longest(["hello", "abcd"]) == "hello"
assert longest(["hello", "abcd", "hi"]) == "hello"
assert longest(["foo"]) == "foo"
assert longest(["1", "22", "333"]) == "333"
assert longest(["5", "4", "3", "2", "1"]) == "5"
