
def right_angle_triangle(a, b, c):
    '''
    Given the lengths of the three sides of a triangle. Return True if the three
    sides form a right-angled triangle, False otherwise.
    A right-angled triangle is a triangle in which one angle is right angle or 
    90 degree.
    Example:
    right_angle_triangle(3, 4, 5) == True
    right_angle_triangle(1, 2, 3) == False
    '''
    return c*c == a*a + b*b
assert right_angle_triangle(3, 4, 5) == True
assert right_angle_triangle(7, 24, 25) == True
assert right_angle_triangle(2, 4, 3) == False
assert right_angle_triangle(9, 8, 16) == False
assert right_angle_triangle(4, 5, 3) == True
assert right_angle_triangle(4, 3, 5) == True
assert right_angle_triangle(3, 5, 4) == True
assert right_angle_triangle(5, 3, 4) == True
assert right_angle_triangle(5, 4, 3) == True
assert right_angle_triangle(12, 5, 13) == True
assert right_angle_triangle(9, 40, 41) == True
assert right_angle_triangle(11, 60, 61) == True
assert right_angle_triangle(20, 21, 29) == True
assert right_angle_triangle(2, 3, 4) == False
assert right_angle_triangle(3, 4, 6) == False
assert right_angle_triangle(4, 6, 8) == False
assert right_angle_triangle(8, 10, 12) == False
assert right_angle_triangle(10, 12, 14) == False
assert right_angle_triangle(3, 3, 3) == False
assert right_angle_triangle(6, 10, 8) == True
assert right_angle_triangle(8, 6, 10) == True
assert right_angle_triangle(8, 10, 6) == True
assert right_angle_triangle(10, 6, 8) == True
assert right_angle_triangle(10, 8, 6) == True
assert right_angle_triangle(5, 6, 7) == False
assert right_angle_triangle(13, 12, 5) == True
assert right_angle_triangle(5, 12, 13) == True
assert right_angle_triangle(100, 100, 10) == False
assert right_angle_triangle(10, 100, 100) == False
assert right_angle_triangle(100, 10, 100) == False
assert right_angle_triangle(3, 4, 10) == False
assert right_angle_triangle(3, 10, 4) == False
assert right_angle_triangle(10, 3, 4) == False
assert right_angle_triangle(4, 3, 6) == False
assert right_angle_triangle(5, 3, 6) == False
assert right_angle_triangle(3, 5, 6) == False
assert right_angle_triangle(4, 5, 6) == False
assert right_angle_triangle(5, 4, 6) == False
assert right_angle_triangle(6, 4, 5) == False
assert right_angle_triangle(6, 5, 4) == False
assert right_angle_triangle(3, 3, 4) == False
assert right_angle_triangle(1, 1, 2) == False
assert right_angle_triangle(4, 4, 5) == False
assert right_angle_triangle(4, 5, 5) == False
assert right_angle_triangle(5, 5, 4) == False
assert right_angle_triangle(5, 4, 5) == False
assert False == right_angle_triangle(10, 8, 3)
assert right_angle_triangle(4, 4, 6) == False
assert right_angle_triangle(4, 4, 4) == False
assert right_angle_triangle(6, 8, 10) == True
assert right_angle_triangle(7, 8, 9) == False
assert right_angle_triangle(9, 7, 8) == False
assert right_angle_triangle(8, 9, 7) == False
assert right_angle_triangle(9, 8, 7) == False
assert right_angle_triangle(8, 7, 9) == False
assert right_angle_triangle(10, 12, 13) == False
assert right_angle_triangle(12, 10, 13) == False
assert right_angle_triangle(13, 12, 10) == False
assert False == right_angle_triangle(5, 3, 3)
assert right_angle_triangle(1, 1, 1) == False
assert right_angle_triangle(3, 4, 7) == False
assert right_angle_triangle(3, 7, 4) == False
assert right_angle_triangle(7, 3, 4) == False
assert right_angle_triangle(7, 4, 3) == False
assert right_angle_triangle(4, 7, 3) == False
assert right_angle_triangle(4, 3, 7) == False
assert right_angle_triangle(0, 4, 5) == False
assert right_angle_triangle(0, 5, 4) == False
assert right_angle_triangle(5, 0, 4) == False
assert right_angle_triangle(5, 4, 0) == False
assert right_angle_triangle(4, 5, 0) == False
assert right_angle_triangle(12, 13, 5) == True
assert right_angle_triangle(15, 8, 17) == True
assert right_angle_triangle(8, 15, 17) == True
assert right_angle_triangle(8, 17, 15) == True
assert right_angle_triangle(17, 8, 15) == True
assert right_angle_triangle(17, 15, 8) == True
assert right_angle_triangle(15, 17, 8) == True
assert right_angle_triangle(4, 6, 3) == False
assert False == right_angle_triangle(10, 10, 10)
assert right_angle_triangle(5, 5, 5) == False
assert right_angle_triangle(10, 20, 30) == False
assert right_angle_triangle(2, 3, 5) == False
assert right_angle_triangle(3, 5, 7) == False
assert right_angle_triangle(5, 3, 7) == False
assert right_angle_triangle(4, 5, 7) == False
assert right_angle_triangle(13, 5, 12) == True
assert right_angle_triangle(5, 13, 12) == True
assert right_angle_triangle(3, 6, 4) == False
assert right_angle_triangle(6, 3, 4) == False
assert right_angle_triangle(3, 5, 4) is True
assert right_angle_triangle(3, 4, 6) is False
assert right_angle_triangle(3, 6, 4) is False
assert right_angle_triangle(6, 3, 4) is False
assert right_angle_triangle(3, 4, 2) is False
assert right_angle_triangle(2, 3, 4) is False
assert right_angle_triangle(2, 4, 3) is False
assert right_angle_triangle(1, 1, 1) is False
assert right_angle_triangle(1, 2, 3) is False
assert right_angle_triangle(1, 3, 2) is False
assert right_angle_triangle(3, 1, 2) is False
assert right_angle_triangle(5, 12, 13) is True
assert right_angle_triangle(5, 13, 12) is True
assert right_angle_triangle(7, 24, 25) is True
assert right_angle_triangle(7, 25, 24) is True
assert right_angle_triangle(8, 15, 17) is True
assert False == right_angle_triangle(3, 4, 6)
assert False == right_angle_triangle(4, 5, 6)
assert True == right_angle_triangle(3, 5, 4)
assert False == right_angle_triangle(3, 4, 4)
assert right_angle_triangle(5, 7, 9) == False
assert right_angle_triangle(12, 16, 20) == True
assert right_angle_triangle(6, 4, 3) == False
assert right_angle_triangle(3, 7, 5) == False
assert right_angle_triangle(7, 3, 5) == False
assert right_angle_triangle(7, 5, 3) == False
assert right_angle_triangle(5, 7, 3) == False
assert right_angle_triangle(10, 5, 7) == False
assert right_angle_triangle(3, 4, 4) == False
assert right_angle_triangle(4, 4, 3) == False
assert right_angle_triangle(4, 3, 3) == False
assert right_angle_triangle(5, 4, 2) == False
assert False == right_angle_triangle(1, 1, 2)
assert right_angle_triangle(9, 12, 8) == False
assert right_angle_triangle(4, 8, 16) == False
assert right_angle_triangle(5, 3, 3) == False
assert right_angle_triangle(2, 3, 6) == False
assert False == right_angle_triangle(3, 4, 2)
assert right_angle_triangle(3, 6, 9) == False
assert right_angle_triangle(0, 4, 3) == False
assert right_angle_triangle(0, 0, 4) == False
assert right_angle_triangle(0, 4, 0) == False
assert right_angle_triangle(3, 0, 0) == False
assert right_angle_triangle(3, 0, 4) == False
assert right_angle_triangle(3, 4, 0) == False
assert right_angle_triangle(15, 18, 6) == False
assert right_angle_triangle(9, 4, 3) == False
assert right_angle_triangle(4, 9, 3) == False
assert right_angle_triangle(4, 3, 4) == False
assert right_angle_triangle(5, 2, 4) == False
assert right_angle_triangle(4, 6, 5) == False
assert right_angle_triangle(5, 6, 4) == False
assert False == right_angle_triangle(3, 6, 5)
assert False == right_angle_triangle(4, 6, 5)
assert False == right_angle_triangle(5, 4, 6)
assert False == right_angle_triangle(5, 6, 4)
assert False == right_angle_triangle(6, 4, 5)
assert False == right_angle_triangle(6, 5, 4)
assert False == right_angle_triangle(1, 2, 3)
assert False == right_angle_triangle(3, 1, 2)
assert False == right_angle_triangle(2, 3, 1)
assert False == right_angle_triangle(2, 1, 3)
assert False == right_angle_triangle(1, 3, 2)
assert False == right_angle_triangle(3, 2, 1)
assert False == right_angle_triangle(1, 1, 1)
assert False == right_angle_triangle(2, 2, 2)
assert right_angle_triangle(1, 2, 3) == False
assert right_angle_triangle(6, 6, 6) == False
assert right_angle_triangle(2, 2, 3) == False
assert right_angle_triangle(1, 0, 2) == False
assert right_angle_triangle(4, 6, 7) == False
assert right_angle_triangle(4, 7, 6) == False
assert right_angle_triangle(6, 4, 7) == False
assert right_angle_triangle(6, 7, 4) == False
assert right_angle_triangle(7, 4, 6) == False
assert right_angle_triangle(7, 6, 4) == False
assert right_angle_triangle(10, 10, 14) == False
assert right_angle_triangle(10, 14, 10) == False
assert right_angle_triangle(14, 10, 10) == False
assert right_angle_triangle(2, 2, 2) == False
assert right_angle_triangle(2, 2, 1) == False
assert right_angle_triangle(29, 420, 421) == True
assert right_angle_triangle(29, 421, 420) == True
assert right_angle_triangle(1, 2, 2) == False
assert right_angle_triangle(1, 1, 3) == False
assert right_angle_triangle(10, 12, 10) == False
assert right_angle_triangle(1, 1, 10) == False
assert right_angle_triangle(9, 10, 14) == False
assert right_angle_triangle(9, 14, 10) == False
assert right_angle_triangle(10, 9, 14) == False
assert right_angle_triangle(10, 14, 9) == False
assert right_angle_triangle(14, 9, 10) == False
assert right_angle_triangle(14, 10, 9) == False
assert right_angle_triangle(7, 4, 5) == False
assert right_angle_triangle(3, 1, 2) == False
assert right_angle_triangle(2, 3, 1) == False
assert right_angle_triangle(2, 1, 3) == False
assert right_angle_triangle(1, 3, 2) == False
assert right_angle_triangle(3, 2, 4) == False
assert right_angle_triangle(2, 1, 2) == False
assert right_angle_triangle(4, 2, 3) == False
assert right_angle_triangle(3, 4, 8) == False
assert right_angle_triangle(3, 4, 1) == False
assert right_angle_triangle(3, 4, 5.00001) == False
