

def flip_case(string: str) -> str:
    """ For a given string, flip lowercase characters to uppercase and uppercase to lowercase.
    >>> flip_case('Hello')
    'hELLO'
    """
    return string.lower()
assert flip_case("") == ""
assert flip_case("aBbA") == "AbBa"
assert flip_case("abc") == "ABC"
assert flip_case("TeSt") == "tEsT"
assert flip_case("aBcDeF") == "AbCdEf"
assert "K" == flip_case("k")
assert "GJH" == flip_case("gjh")
assert flip_case("BOBBY") == "bobby"
assert flip_case("BoBbY") == "bObBy"
assert flip_case("racecar") == "RACECAR"
assert flip_case("AaBbCc") == "aAbBcC"
assert flip_case("HotCoding") == "hOTcODING"
assert flip_case("Jackpot") == "jACKPOT"
assert flip_case("NONE") == "none"
assert flip_case("a") == "A"
assert flip_case("abcde") == "ABCDE"
assert flip_case("ZZzz") == "zzZZ"
assert flip_case("HELLO") == "hello"
assert flip_case("Übermensch") == "üBERMENSCH"
assert flip_case("ABCDE") == "abcde"
assert flip_case("aBcDe") == "AbCdE"
assert flip_case("lEaVe") == "LeAvE"
assert flip_case("aBcDeFgHiJkLmNoPqRsTuVwXyZ") == "AbCdEfGhIjKlMnOpQrStUvWxYz"
assert flip_case("WOW") == "wow"
assert flip_case("abCd") == "ABcD"
assert flip_case("AbCd") == "aBcD"
assert flip_case("abCdEfGhIjKlMnOpQrStUvWxYz") == "ABcDeFgHiJkLmNoPqRsTuVwXyZ"
assert flip_case("AbCdEfGhIjKlMnOpQrStUvWxYz") == "aBcDeFgHiJkLmNoPqRsTuVwXyZ"
assert flip_case("world") == "WORLD"
assert flip_case("WORLD") == "world"
assert flip_case("hELLO") == "Hello"
assert flip_case("A") == "a"
assert flip_case("aBcDeFg") == "AbCdEfG"
assert flip_case("Apple") == "aPPLE"
assert flip_case("cHECK") == "Check"
assert flip_case("Cat") == "cAT"
assert flip_case("OK") == "ok"
assert flip_case("teSt") == "TEsT"
assert flip_case("aBc") == "AbC"
assert flip_case("ABC") == "abc"
assert flip_case("sToRm") == "StOrM"
assert flip_case("hEllO") == "HeLLo"
assert flip_case("PYTHON") == "python"
assert flip_case("LoWeRcAsE") == "lOwErCaSe"
assert flip_case("Test") == "tEST"
assert flip_case("T") == "t"
assert flip_case("t") == "T"
assert '' == flip_case('')
assert flip_case("aBcDfGh") == "AbCdFgH"
assert flip_case("flipMEover") == "FLIPmeOVER"
assert flip_case("abcdef") == "ABCDEF"
assert flip_case("AAAAA") == "aaaaa"
assert flip_case("FlipCase") == "fLIPcASE"
assert flip_case("hEllo") == "HeLLO"
assert flip_case("test") == "TEST"
assert flip_case("ThIs") == "tHiS"
assert flip_case("aSdF") == "AsDf"
assert flip_case("qwErTy") == "QWeRtY"
assert flip_case("aA") == "Aa"
assert flip_case("Aa") == "aA"
assert flip_case("TEST") == "test"
assert flip_case("SHHHH") == "shhhh"
assert flip_case("shhhh") == "SHHHH"
assert 'HELLO' == flip_case('hello')
assert flip_case("kEY") == "Key"
