
def bf(planet1, planet2):
    '''
    There are eight planets in our solar system: the closerst to the Sun 
    is Mercury, the next one is Venus, then Earth, Mars, Jupiter, Saturn, 
    Uranus, Neptune.
    Write a function that takes two planet names as strings planet1 and planet2. 
    The function should return a tuple containing all planets whose orbits are 
    located between the orbit of planet1 and the orbit of planet2, sorted by 
    the proximity to the sun. 
    The function should return an empty tuple if planet1 or planet2
    are not correct planet names. 
    Examples
    bf("Jupiter", "Neptune") ==> ("Saturn", "Uranus")
    bf("Earth", "Mercury") ==> ("Venus")
    bf("Mercury", "Uranus") ==> ("Venus", "Earth", "Mars", "Jupiter", "Saturn")
    '''
    planet_names = ("Mercury", "Venus", "Earth", "Mars", "Jupyter", "Saturn", "Uranus", "Neptune")
    if planet1 not in planet_names or planet2 not in planet_names or planet1 == planet2:
        return ()
    planet1_index = planet_names.index(planet1)
    planet2_index = planet_names.index(planet2)
    if planet1_index < planet2_index:
        return (planet_names[planet1_index + 1: planet2_index])
    else:
        return (planet_names[planet2_index + 1 : planet1_index])
assert bf("Mars", "Jupiter") == ()
assert bf('Earth', 'Neptune') == ('Mars', 'Jupiter', 'Saturn', 'Uranus')
assert bf('Mars', 'Mars') == ()
assert bf('Mercury', 'Pluto') == ()
assert bf('Uranus', 'Neptune') == ()
assert bf('Mercury', 'Neptune') == ('Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus')
assert bf('Mars', 'Earth') == ()
assert bf('Venus', 'Mercury') == ()
assert bf('Venus', 'Uranus') == ('Earth', 'Mars', 'Jupiter', 'Saturn')
assert bf('Earth', 'Saturn') == ('Mars', 'Jupiter')
assert bf('Mars', 'Jupiter') == ()
assert bf('Jupiter', 'Mars') == ()
assert bf('Saturn', 'Saturn') == ()
assert bf('Uranus', 'Uranus') == ()
assert bf('Neptune', 'Neptune') == ()
assert bf('Pluto', 'Neptune') == ()
assert bf('Earth', 'Pluto') == ()
assert bf('Pluto', 'Venus') == ()
assert bf('Pluto', 'Pluto') == ()
assert bf('Mercury', 'Venus') == ()
assert bf('Venus', 'Mars') == ('Earth',)
assert bf("Pluto", "Mars") == ()
assert bf("Jupiter", "Pluto") == ()
assert bf('Earth', 'Neptune') == ('Mars', 'Jupiter', 'Saturn', 'Uranus',)
assert bf('Mercury', 'Neptune') == ('Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus',)
assert bf('Pluto', 'Mars') == ()
assert bf('Venus', 'Saturn') == ('Earth', 'Mars', 'Jupiter')
assert bf('Jupiter', 'Neptune') == ('Saturn', 'Uranus')
assert bf('Saturn', 'Neptune') == ('Uranus',)
assert bf('Venus', 'Pluto') == ()
assert bf('Earth', 'Earth') == ()
assert bf('Mars', 'Venus') == ('Earth',)
assert bf('Neptune', 'Earth') == ('Mars', 'Jupiter', 'Saturn', 'Uranus')
assert bf('Mercury', 'Uranus') == ('Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn')
assert bf('Uranus', 'Mercury') == ('Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn')
assert bf('Neptune', 'Pluto') == ()
assert bf('Venus', 'Venus') == ()
assert bf('Earth', 'Mars') == ()
assert bf("Mercury", "Pluto") == ()
assert bf("Pluto", "Neptune") == ()
assert bf("Mars", "Pluto") == ()
assert bf("Pluto", "Uranus") == ()
assert bf("Venus", "Pluto") == ()
assert bf("Earth", "Earth") == ()
assert bf('Mars', 'Neptune') == ('Jupiter', 'Saturn', 'Uranus')
assert bf("Mars", "Neptune") == ("Jupiter", "Saturn", "Uranus")
assert bf("Earth", "Uranus") == ("Mars", "Jupiter", "Saturn")
assert bf("Venus", "Jupiter") == ("Earth", "Mars")
assert bf("Uranus", "Neptune") == ()
assert bf("Earth", "Mars") == ()
assert bf("Saturn", "Pluto") == ()
assert bf("Mercury", "Saturn") == ("Venus", "Earth", "Mars", "Jupiter")
assert bf("Pluto", "Saturn") == ()
assert bf("Mars", "Mars") == ()
assert bf("Mercury", "Venus") == ()
assert bf("Mars", "Earth") == ()
assert bf('Saturn', 'Jupiter') == ()
assert bf("Earth", "Neptune") == ("Mars", "Jupiter", "Saturn", "Uranus")
assert bf("Saturn", "Jupiter") == ()
assert bf('Mercury', 'Saturn') == ('Venus', 'Earth', 'Mars', 'Jupiter')
assert bf('Saturn', 'Mercury') == ('Venus', 'Earth', 'Mars', 'Jupiter')
assert bf('Venus', 'Neptune') == ('Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus')
assert bf('Neptune', 'Venus') == ('Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus')
assert bf('Pluto', 'Earth') == ()
assert bf('Mars', 'Pluto') == ()
assert bf('Venus', 'Jupiter') == ('Earth', 'Mars')
assert bf('Uranus', 'Saturn') == ()
assert bf("Mercury", "Neptune") == ("Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus")
assert bf("Earth", "Pluto") == ()
assert bf('Saturn', 'Pluto') == ()
assert bf("Neptune", "Uranus") == ()
