
def int_to_mini_roman(number):
    """
    Given a positive integer, obtain its roman numeral equivalent as a string,
    and return it in lowercase.
    Restrictions: 1 <= num <= 1000

    Examples:
    >>> int_to_mini_roman(19) == 'xix'
    >>> int_to_mini_roman(152) == 'clii'
    >>> int_to_mini_roman(426) == 'cdxxvi'
    """
    num = [1, 4, 5, 9, 10, 40, 50, 90,  
           100, 400, 500, 900, 1000] 
    sym = ["I", "IV", "V", "IX", "X", "XL",  
           "L", "XC", "C", "CD", "D", "CM", "M"] 
    i = 12
    res = ''
    while number: 
        div = number // num[i] 
        number %= num[i] 
        while div: 
            res += sym[i]
        i -= 1
    return res.lower()
assert int_to_mini_roman(1) == 'i'
assert int_to_mini_roman(4) == 'iv'
assert int_to_mini_roman(9) == 'ix'
assert int_to_mini_roman(13) == 'xiii'
assert int_to_mini_roman(40) == 'xl'
assert int_to_mini_roman(99) == 'xcix'
assert int_to_mini_roman(500) == 'd'
assert int_to_mini_roman(1000) == 'm'
assert int_to_mini_roman(5) == 'v'
assert int_to_mini_roman(10) == 'x'
assert int_to_mini_roman(50) == 'l'
assert int_to_mini_roman(100) == 'c'
assert int_to_mini_roman(90) == 'xc'
assert int_to_mini_roman(400) == 'cd'
assert int_to_mini_roman(900) == 'cm'
assert int_to_mini_roman(3999) == 'mmmcmxcix'
assert int_to_mini_roman(11) == 'xi'
assert int_to_mini_roman(19) == 'xix'
assert int_to_mini_roman(4) == "iv"
assert int_to_mini_roman(9) == "ix"
assert int_to_mini_roman(21) == "xxi"
assert int_to_mini_roman(100) == "c"
assert int_to_mini_roman(500) == "d"
assert int_to_mini_roman(1000) == "m"
assert int_to_mini_roman(5) == "v"
assert int_to_mini_roman(10) == "x"
assert int_to_mini_roman(50) == "l"
assert int_to_mini_roman(40) == "xl"
assert int_to_mini_roman(90) == "xc"
assert int_to_mini_roman(400) == "cd"
assert int_to_mini_roman(900) == "cm"
assert int_to_mini_roman(3999) == "mmmcmxcix"
assert int_to_mini_roman(444) == 'cdxliv'
assert int_to_mini_roman(999) == 'cmxcix'
assert int_to_mini_roman(14) == 'xiv'
assert int_to_mini_roman(2) == 'ii'
assert int_to_mini_roman(3) == 'iii'
assert int_to_mini_roman(6) == 'vi'
assert int_to_mini_roman(7) == 'vii'
assert int_to_mini_roman(8) == 'viii'
assert int_to_mini_roman(12) == 'xii'
assert int_to_mini_roman(15) == 'xv'
assert int_to_mini_roman(16) == 'xvi'
assert int_to_mini_roman(17) == 'xvii'
assert int_to_mini_roman(18) == 'xviii'
assert int_to_mini_roman(20) == 'xx'
assert int_to_mini_roman(21) == 'xxi'
assert int_to_mini_roman(22) == 'xxii'
assert int_to_mini_roman(23) == 'xxiii'
assert int_to_mini_roman(24) == 'xxiv'
assert int_to_mini_roman(25) == 'xxv'
assert int_to_mini_roman(26) == 'xxvi'
assert int_to_mini_roman(27) == 'xxvii'
assert int_to_mini_roman(28) == 'xxviii'
assert int_to_mini_roman(29) == 'xxix'
assert int_to_mini_roman(30) == 'xxx'
assert int_to_mini_roman(31) == 'xxxi'
assert int_to_mini_roman(32) == 'xxxii'
assert int_to_mini_roman(33) == 'xxxiii'
assert int_to_mini_roman(34) == 'xxxiv'
assert int_to_mini_roman(35) == 'xxxv'
assert int_to_mini_roman(36) == 'xxxvi'
assert int_to_mini_roman(37) == 'xxxvii'
assert int_to_mini_roman(38) == 'xxxviii'
assert int_to_mini_roman(39) == 'xxxix'
assert int_to_mini_roman(41) == 'xli'
assert int_to_mini_roman(42) == 'xlii'
assert int_to_mini_roman(43) == 'xliii'
assert int_to_mini_roman(44) == 'xliv'
assert int_to_mini_roman(45) == 'xlv'
assert int_to_mini_roman(46) == 'xlvi'
assert int_to_mini_roman(47) == 'xlvii'
assert int_to_mini_roman(48) == 'xlviii'
assert int_to_mini_roman(49) == 'xlix'
assert int_to_mini_roman(51) == 'li'
assert int_to_mini_roman(52) == 'lii'
assert int_to_mini_roman(53) == 'liii'
assert int_to_mini_roman(54) == 'liv'
assert int_to_mini_roman(55) == 'lv'
assert int_to_mini_roman(56) == 'lvi'
assert int_to_mini_roman(57) == 'lvii'
assert int_to_mini_roman(58) == 'lviii'
assert int_to_mini_roman(59) == 'lix'
assert int_to_mini_roman(60) == 'lx'
assert int_to_mini_roman(61) == 'lxi'
assert int_to_mini_roman(62) == 'lxii'
assert int_to_mini_roman(63) == 'lxiii'
assert int_to_mini_roman(64) == 'lxiv'
assert int_to_mini_roman(65) == 'lxv'
assert int_to_mini_roman(66) == 'lxvi'
assert int_to_mini_roman(67) == 'lxvii'
assert int_to_mini_roman(68) == 'lxviii'
assert int_to_mini_roman(69) == 'lxix'
assert int_to_mini_roman(70) == 'lxx'
assert int_to_mini_roman(71) == 'lxxi'
assert int_to_mini_roman(72) == 'lxxii'
assert int_to_mini_roman(73) == 'lxxiii'
assert int_to_mini_roman(27) == "xxvii"
assert int_to_mini_roman(3) == "iii"
assert int_to_mini_roman(15) == "xv"
assert int_to_mini_roman(234) == "ccxxxiv"
assert int_to_mini_roman(999) == "cmxcix"
assert int_to_mini_roman(456) == "cdlvi"
assert int_to_mini_roman(123) == "cxxiii"
assert int_to_mini_roman(765) == "dcclxv"
assert int_to_mini_roman(111) == "cxi"
assert int_to_mini_roman(222) == "ccxxii"
assert int_to_mini_roman(333) == "cccxxxiii"
assert int_to_mini_roman(444) == "cdxliv"
assert int_to_mini_roman(555) == "dlv"
assert int_to_mini_roman(666) == "dclxvi"
assert int_to_mini_roman(777) == "dcclxxvii"
assert int_to_mini_roman(11) == "xi"
assert int_to_mini_roman(12) == "xii"
assert int_to_mini_roman(13) == "xiii"
assert int_to_mini_roman(14) == "xiv"
assert int_to_mini_roman(16) == "xvi"
assert int_to_mini_roman(17) == "xvii"
assert int_to_mini_roman(18) == "xviii"
assert int_to_mini_roman(19) == "xix"
assert int_to_mini_roman(20) == "xx"
assert int_to_mini_roman(22) == "xxii"
assert int_to_mini_roman(23) == "xxiii"
assert int_to_mini_roman(24) == "xxiv"
assert int_to_mini_roman(25) == "xxv"
assert int_to_mini_roman(26) == "xxvi"
assert int_to_mini_roman(28) == "xxviii"
assert int_to_mini_roman(29) == "xxix"
assert int_to_mini_roman(30) == "xxx"
assert int_to_mini_roman(31) == "xxxi"
assert int_to_mini_roman(32) == "xxxii"
assert int_to_mini_roman(33) == "xxxiii"
assert int_to_mini_roman(34) == "xxxiv"
assert int_to_mini_roman(35) == "xxxv"
assert int_to_mini_roman(36) == "xxxvi"
assert int_to_mini_roman(37) == "xxxvii"
assert int_to_mini_roman(38) == "xxxviii"
assert int_to_mini_roman(39) == "xxxix"
assert int_to_mini_roman(41) == "xli"
assert int_to_mini_roman(42) == "xlii"
assert int_to_mini_roman(43) == "xliii"
assert int_to_mini_roman(44) == "xliv"
assert int_to_mini_roman(45) == "xlv"
assert int_to_mini_roman(46) == "xlvi"
assert int_to_mini_roman(47) == "xlvii"
assert int_to_mini_roman(48) == "xlviii"
assert int_to_mini_roman(49) == "xlix"
assert int_to_mini_roman(51) == "li"
assert int_to_mini_roman(52) == "lii"
assert int_to_mini_roman(53) == "liii"
assert int_to_mini_roman(54) == "liv"
assert int_to_mini_roman(55) == "lv"
assert int_to_mini_roman(56) == "lvi"
assert int_to_mini_roman(1001) == 'mi'
assert int_to_mini_roman(1002) == 'mii'
assert int_to_mini_roman(1003) == 'miii'
assert int_to_mini_roman(1004) == 'miv'
assert int_to_mini_roman(1005) == 'mv'
assert int_to_mini_roman(1006) == 'mvi'
assert int_to_mini_roman(1007) == 'mvii'
assert int_to_mini_roman(1008) == 'mviii'
assert int_to_mini_roman(1009) == 'mix'
assert int_to_mini_roman(1010) == 'mx'
assert int_to_mini_roman(1011) == 'mxi'
assert int_to_mini_roman(1012) == 'mxii'
assert int_to_mini_roman(1013) == 'mxiii'
assert int_to_mini_roman(1014) == 'mxiv'
assert int_to_mini_roman(1015) == 'mxv'
assert int_to_mini_roman(1016) == 'mxvi'
assert int_to_mini_roman(1017) == 'mxvii'
assert int_to_mini_roman(1018) == 'mxviii'
assert int_to_mini_roman(1019) == 'mxix'
assert int_to_mini_roman(1020) == 'mxx'
assert int_to_mini_roman(1021) == 'mxxi'
assert int_to_mini_roman(1022) == 'mxxii'
assert int_to_mini_roman(1023) == 'mxxiii'
assert int_to_mini_roman(1024) == 'mxxiv'
assert int_to_mini_roman(1025) == 'mxxv'
assert int_to_mini_roman(1026) == 'mxxvi'
assert int_to_mini_roman(1027) == 'mxxvii'
assert int_to_mini_roman(1028) == 'mxxviii'
assert int_to_mini_roman(1029) == 'mxxix'
assert int_to_mini_roman(1030) == 'mxxx'
assert int_to_mini_roman(1031) == 'mxxxi'
assert int_to_mini_roman(1032) == 'mxxxii'
assert int_to_mini_roman(1033) == 'mxxxiii'
assert int_to_mini_roman(1034) == 'mxxxiv'
assert int_to_mini_roman(1035) == 'mxxxv'
assert int_to_mini_roman(1036) == 'mxxxvi'
assert int_to_mini_roman(1037) == 'mxxxvii'
assert int_to_mini_roman(1038) == 'mxxxviii'
assert int_to_mini_roman(1039) == 'mxxxix'
assert int_to_mini_roman(1040) == 'mxl'
assert int_to_mini_roman(1041) == 'mxli'
assert int_to_mini_roman(1042) == 'mxlii'
assert int_to_mini_roman(1043) == 'mxliii'
assert int_to_mini_roman(1044) == 'mxliv'
assert int_to_mini_roman(1045) == 'mxlv'
assert int_to_mini_roman(1046) == 'mxlvi'
assert int_to_mini_roman(1047) == 'mxlvii'
assert int_to_mini_roman(1048) == 'mxlviii'
assert int_to_mini_roman(1049) == 'mxlix'
assert int_to_mini_roman(1050) == 'ml'
assert int_to_mini_roman(1051) == 'mli'
assert int_to_mini_roman(1052) == 'mlii'
assert int_to_mini_roman(1053) == 'mliii'
assert int_to_mini_roman(79) == 'lxxix'
assert int_to_mini_roman(89) == 'lxxxix'
assert int_to_mini_roman(101) == 'ci'
assert int_to_mini_roman(111) == 'cxi'
assert int_to_mini_roman(121) == 'cxxi'
assert int_to_mini_roman(131) == 'cxxxi'
assert int_to_mini_roman(141) == 'cxli'
assert int_to_mini_roman(151) == 'cli'
assert int_to_mini_roman(161) == 'clxi'
assert int_to_mini_roman(171) == 'clxxi'
assert int_to_mini_roman(181) == 'clxxxi'
assert int_to_mini_roman(199) == 'cxcix'
assert int_to_mini_roman(401) == 'cdi'
assert int_to_mini_roman(411) == 'cdxi'
assert int_to_mini_roman(421) == 'cdxxi'
assert int_to_mini_roman(431) == 'cdxxxi'
assert int_to_mini_roman(441) == 'cdxli'
assert int_to_mini_roman(451) == 'cdli'
assert int_to_mini_roman(461) == 'cdlxi'
assert int_to_mini_roman(471) == 'cdlxxi'
assert int_to_mini_roman(481) == 'cdlxxxi'
assert int_to_mini_roman(499) == 'cdxcix'
assert int_to_mini_roman(501) == 'di'
assert int_to_mini_roman(511) == 'dxi'
assert int_to_mini_roman(521) == 'dxxi'
assert int_to_mini_roman(531) == 'dxxxi'
assert int_to_mini_roman(541) == 'dxli'
assert int_to_mini_roman(551) == 'dli'
assert int_to_mini_roman(561) == 'dlxi'
assert int_to_mini_roman(571) == 'dlxxi'
assert int_to_mini_roman(581) == 'dlxxxi'
assert int_to_mini_roman(599) == 'dxcix'
assert int_to_mini_roman(601) == 'dci'
assert int_to_mini_roman(611) == 'dcxi'
assert int_to_mini_roman(621) == 'dcxxi'
assert int_to_mini_roman(631) == 'dcxxxi'
assert int_to_mini_roman(641) == 'dcxli'
assert int_to_mini_roman(651) == 'dcli'
assert int_to_mini_roman(661) == 'dclxi'
assert int_to_mini_roman(671) == 'dclxxi'
assert int_to_mini_roman(681) == 'dclxxxi'
assert int_to_mini_roman(699) == 'dcxcix'
assert int_to_mini_roman(80) == 'lxxx'
assert int_to_mini_roman(95) == 'xcv'
assert int_to_mini_roman(105) == 'cv'
assert int_to_mini_roman(110) == 'cx'
assert int_to_mini_roman(150) == 'cl'
assert int_to_mini_roman(200) == 'cc'
assert int_to_mini_roman(250) == 'ccl'
assert int_to_mini_roman(300) == 'ccc'
assert int_to_mini_roman(600) == 'dc'
assert int_to_mini_roman(700) == 'dcc'
assert int_to_mini_roman(800) == 'dccc'
assert int_to_mini_roman(950) == 'cml'
assert int_to_mini_roman(399) == 'cccxcix'
assert int_to_mini_roman(2000) == 'mm'
assert int_to_mini_roman(99) == "xcix"
assert int_to_mini_roman(199) == "cxcix"
assert int_to_mini_roman(399) == "cccxcix"
assert int_to_mini_roman(1001) == "mi"
assert int_to_mini_roman(1002) == "mii"
assert int_to_mini_roman(1003) == "miii"
assert int_to_mini_roman(1004) == "miv"
assert int_to_mini_roman(1005) == "mv"
assert int_to_mini_roman(1006) == "mvi"
assert int_to_mini_roman(1007) == "mvii"
assert int_to_mini_roman(1008) == "mviii"
assert int_to_mini_roman(1009) == "mix"
assert int_to_mini_roman(1010) == "mx"
assert int_to_mini_roman(1011) == "mxi"
assert int_to_mini_roman(1012) == "mxii"
assert int_to_mini_roman(1013) == "mxiii"
assert int_to_mini_roman(1014) == "mxiv"
assert int_to_mini_roman(1015) == "mxv"
assert int_to_mini_roman(1016) == "mxvi"
assert int_to_mini_roman(1017) == "mxvii"
assert int_to_mini_roman(1018) == "mxviii"
assert int_to_mini_roman(1019) == "mxix"
assert int_to_mini_roman(1020) == "mxx"
assert int_to_mini_roman(1021) == "mxxi"
assert int_to_mini_roman(1022) == "mxxii"
assert int_to_mini_roman(1023) == "mxxiii"
assert int_to_mini_roman(1024) == "mxxiv"
assert int_to_mini_roman(1025) == "mxxv"
assert int_to_mini_roman(1026) == "mxxvi"
assert int_to_mini_roman(1027) == "mxxvii"
assert int_to_mini_roman(1028) == "mxxviii"
assert int_to_mini_roman(1029) == "mxxix"
assert int_to_mini_roman(1030) == "mxxx"
assert int_to_mini_roman(1031) == "mxxxi"
assert int_to_mini_roman(1032) == "mxxxii"
assert int_to_mini_roman(1033) == "mxxxiii"
assert int_to_mini_roman(1034) == "mxxxiv"
assert int_to_mini_roman(1035) == "mxxxv"
assert int_to_mini_roman(1036) == "mxxxvi"
assert int_to_mini_roman(1037) == "mxxxvii"
assert int_to_mini_roman(1038) == "mxxxviii"
assert int_to_mini_roman(1039) == "mxxxix"
assert int_to_mini_roman(1040) == "mxl"
assert int_to_mini_roman(1041) == "mxli"
assert int_to_mini_roman(1042) == "mxlii"
assert int_to_mini_roman(1043) == "mxliii"
assert int_to_mini_roman(1044) == "mxliv"
assert int_to_mini_roman(1045) == "mxlv"
assert int_to_mini_roman(1046) == "mxlvi"
assert int_to_mini_roman(1047) == "mxlvii"
assert int_to_mini_roman(1048) == "mxlviii"
assert int_to_mini_roman(1049) == "mxlix"
assert int_to_mini_roman(1050) == "ml"
assert int_to_mini_roman(101) == "ci"
assert int_to_mini_roman(150) == "cl"
assert int_to_mini_roman(499) == "cdxcix"
assert int_to_mini_roman(1051)
assert int_to_mini_roman(2) == "ii"
assert int_to_mini_roman(6) == "vi"
assert int_to_mini_roman(7) == "vii"
assert int_to_mini_roman(8) == "viii"
assert int_to_mini_roman(349) == 'cccxlix'
assert int_to_mini_roman(789) == 'dcclxxxix'
